/**
 * generated by Xtext
 */
package com.uniandes.config2sql.xtext.validation;

import com.uniandes.config2sql.xtext.validation.AbstractConfigValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ConfigValidator extends AbstractConfigValidator {
}
