/**
 * generated by Xtext
 */
package com.uniandes.jsontosql.xtext.ui.contentassist;

import com.uniandes.jsontosql.xtext.ui.contentassist.AbstractJsonProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class JsonProposalProvider extends AbstractJsonProposalProvider {
}
