/**
 * generated by Xtext
 */
package com.uniandes.jsontosql.xtext.validation;

import com.uniandes.jsontosql.xtext.validation.AbstractJsonValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class JsonValidator extends AbstractJsonValidator {
}
